apiVersion: v1
kind: Service
metadata:
  name: garden-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: garden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
